version: "3.7"

services:
  devops-web:
    image: $IMAGE_REPO_ENDPOINT/$APP_NAME:$IMAGE_TAG
    ports:
      - "$PORT:$PORT"
    environment:
      REGISTRY_CREDS_USR: $REGISTRY_CREDS_USR
      REGISTRY_CREDS_PSW: $REGISTRY_CREDS_PSW
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_COMMISSION_DB: $MYSQL_COMMISSION_DB
      MYSQL_EMAIL_USERNAME: $MYSQL_EMAIL_USERNAME
      MYSQL_EMAIL_PASSWORD: $MYSQL_EMAIL_PASSWORD
      MYSQL_EMAIL_HOST: $MYSQL_EMAIL_HOST
      MYSQL_EMAIL_PORT: $MYSQL_EMAIL_PORT
      MYSQL_EMAIL_DB: $MYSQL_EMAIL_DB
      TIMER_MONGO_USER: $TIMER_MONGO_USER
      TIMER_MONGO_PASSWORD: $TIMER_MONGO_PASSWORD
      TIMER_MONGO_HOST: $TIMER_MONGO_HOST
      TIMER_MONGO_DB: $TIMER_MONGO_DB
      KEY_TIME_BEGIN: $KEY_TIME_BEGIN
      KEY_TIME_END: $KEY_TIME_END
      SERVER_URL: $SERVER_URL
      OVER_TIME: $OVER_TIME
      CPA_DATE_FROM: $CPA_DATE_FROM
      CPA_REGDATE: $CPA_REGDATE
      IGNORE_VIP: $IGNORE_VIP
      EMAIL_REGION: $EMAIL_REGION
      EMAIL_IB_REMIND_NOTIFICATION_RECIPIENT: $EMAIL_IB_REMIND_NOTIFICATION_RECIPIENT
      EMAIL_SETTING_NOTIFICATION_RECIPIENT: $EMAIL_SETTING_NOTIFICATION_RECIPIENT
      EMAIL_SUGGEST_SETTING_ALERT_RECIPIENT_1: $EMAIL_SUGGEST_SETTING_ALERT_RECIPIENT_1
      EMAIL_SUGGEST_SETTING_ALERT_RECIPIENT_2: $EMAIL_SUGGEST_SETTING_ALERT_RECIPIENT_2
      EMAIL_SETTING_LINK_IB: $EMAIL_SETTING_LINK_IB
      EMAIL_SETTING_LINK_IB_NON_CONFIRMED: $EMAIL_SETTING_LINK_IB_NON_CONFIRMED
      EMAIL_SETTING_LINK_SALES: $EMAIL_SETTING_LINK_SALES
      EMAIL_SETTING_LINK_SALES_NON_CONFIRMED: $EMAIL_SETTING_LINK_SALES_NON_CONFIRMED

