apiVersion: v1
kind: Service
metadata:
  name: devops-web
  labels:
    app: devops-web
spec:
  ports:
  - name: devops-web
    port: 8003
    targetPort: 8003
    nodePort: 38003
  type: NodePort
  selector:
    app: devops-web

