apiVersion: v1
kind: Service
metadata:
  name: devops
  labels:
    app: devops
spec:
  ports:
  - name: devops
    port: 8000
    targetPort: 8000
    nodePort: 38000
  type: NodePort
  selector:
    app: devops

