apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "devops-web.name" . }}
  environment: {{ .Values.custom.deployment.environment }}
spec:
  host: {{ include "devops-web.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
